package com.layer.atlas.atlasdefault;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.layer.atlas.R;
import com.layer.atlas.viewholder.ConversationViewHolder;
import com.layer.atlas.viewholder.ConversationViewHolderFactory;

public class DefaultConversationViewHolderFactory extends ConversationViewHolderFactory {
    /**
     * Request a new ConversationViewHolder with the given view type.
     *
     * @param viewType The type of ViewHolder to create.
     * @return The ViewHolder generated by the ViewHolderFactory.
     */
    @Override
    public ConversationViewHolder createViewHolder(ViewGroup viewGroup, int viewType) {
        LayoutInflater inflater = LayoutInflater.from(viewGroup.getContext());
        View itemView = inflater.inflate(R.layout.atlas_item_conversation, null);
        return new DefaultConversationViewHolder(itemView);
    }
}
